version: '2'
services:
    productmanagement-app:
        image: productmanagement
        external_links:
            - productmanagement-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/productmanagement?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    productmanagement-mysql:
        extends:
            file: mysql.yml
            service: productmanagement-mysql
